language: node_js
node_js:
    - 10.23.0
branchrs:
    only:
    - master
script:
    - echo "Beginning docker build"
    - docker build -t udagaram-user-api .
    - docker tag udagaram-user-api renjithtech6/udagaram-user-api

after_success:
    - echo "About to create container in Docker registry"
    - echo "$D_PSWD" | docker login -u "$D_UNAME" --password-stdin
    - docker push renjithtech6/udagaram-user-api
